### PR TITLE
[2/3] cleanup static reference

### PR DESCRIPTION
**Pull request by omochi**
- Remove static shared things in ViewController
- Define new singleton class NumswPlayground. 
  This is root component for static objects.
  So it has a RenderViewController.
- Change book initialize code
  `_setupRender` to `NumswPlayground.initialize()`

- Cleanup global function style API implementation
  example:

```
public func addLine(
    x: [Double], y: [Double])
{
    NumswPlayground.shared.addLine(x: x, y: y)
}

public func addLine2(
    x: [Double], y: [Double],
    x2: [Double], y2: [Double])
{
    NumswPlayground.shared.addLine2(x: x, y: y,
                                    x2: x2, y2: y2)
}
```
  
they are simply transfer invocation to singleton instance method.  

- To make sources as many as possible testable on iPad sandbox app,
   split file for codes which need to import `PlaygroundSupport` into `NumswPlayground_Playground.swift` 
  and  all others can  be compiled within iPad app target.

### CODE REVIEW

**Comment by omochi** [comment]
This PR is orthogonal with #9 semantically. 
But it may conflict around `RenderViewController`.
If to be so i will fix it.

**Comment by sonsongithub** [comment]
Is this commit UITableViewController version?

**Comment by omochi** [comment]
@sonsongithub Yes, but I found a new bug with UITableViewController version...

**Comment by omochi** [comment]
Oh, this includes #9 commits.
I will fix this.

**Comment by omochi** [comment]
I switch back to ScrollView.
It is easy to switch back TableView now.

**Comment by omochi** [comment]
now this PR includes #9 

its ready to merge

**Pull request merged**
